#167749946 Setup Swagger
andela/magma-backend pull request #10
Opened 2019-08-22 20:54 UTC by davidteejay

### What does this PR do?
Sets up Swagger Documentation for the project

### Description of Task to be completed?
Created the `swagger.json` file and set up the `/docs` route for viewing the documentation

### How should this be manually tested?
To test:
- Visit the /docs routes in a browser

### What are the relevant pivotal tracker stories?
[#167749946](https://www.pivotaltracker.com/story/show/167749946)

2019-08-23 08:44 UTC, hustlaviola requested changes
Awesome. This is ready to go except for the es5 syntax. Please fix that. Good job

2019-08-23 08:44 UTC, hustlaviola commented on package.json
> +    "swagger-jsdoc": "^3.4.0",
This package seems redundant, you might want to remove it

2019-08-23 08:47 UTC, davidteejay commented
The develop branch is in es5 syntax

2019-08-28 08:50 UTC, hustlaviola approved these changes
Good job

2019-08-30 09:07 UTC, ascii-dev approved these changes
LGTM

2019-08-30 09:07 UTC, merged