#167749943 Setup unit testing
andela/magma-backend pull request #11
Opened 2019-08-24 17:21 UTC by Ibraheem-adeyemo

#### What does this PR do?
- Implement unit testing

#### Description of task to be completed
- Have npm test script working
- Have app.test.js created
- Test http://localhost:3000/

#### How should this be manually tested
- After cloning the repo cd into it and run npm install and npm test

#### What are the relevant pivotal tracker stories

[#167749943](https://www.pivotaltracker.com/story/show/167749943)

2019-08-26 08:19 UTC, davidteejay approved these changes

2019-08-26 08:58 UTC, davidteejay requested changes
For the test and the dev scripts, we should set the node environment in the command. For the test script you should add `NODE_ENV=test` and `NODE_ENV=development` for dev

2019-08-29 10:29 UTC, davidteejay approved these changes

2019-08-29 10:34 UTC, Naimaoye approved these changes

2019-08-29 15:05 UTC, merged