Ch heroku deployment 167749948
andela/magma-backend pull request #12
Opened 2019-08-26 05:30 UTC by daviddamilola

#### What does this PR do?
 Deploys barefoot nomad base application to Heroku
#### Description of Task to be completed?
* Add heroku.yml 
* Add app.json
#### How should this be manually tested?
* Access the repo from https://magma-backend-staging.herokuapp.com/
#### Any background context you want to provide?
* To deploy develop branch, the branch with the start script will have to be merged.
* To enable app reviews this branch will have to be merged with the develop branch, else heroku will add a commit to develop.  
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/167749948
#### Screenshots (if appropriate)
NILL
#### Questions:
NILL

2019-08-26 06:01 UTC, hustlaviola requested changes
Good job on this PR. You can change the *Relevant PT story* to display just the story id by following this format
`[story_id](https://www.pivotaltracker.com/story/show/story_id)`

2019-08-26 08:19 UTC, daviddamilola commented
> Good job on this PR. You can change the _Relevant PT story_ to display just the story id by following this format
> [story_id](https://www.pivotaltracker.com/story/show/story_id)

changes have been implemented.

2019-08-26 08:23 UTC, davidteejay requested changes
In the `app.json`, are you not supposed to put environment variables inside the `env` object?

2019-08-26 08:30 UTC, davidteejay reviewed
And also, you need to change the title. You can look at the other PRs for reference

2019-08-26 15:34 UTC, davidteejay approved these changes

2019-08-26 16:00 UTC, davidteejay approved these changes

2019-08-27 13:34 UTC, Naimaoye reviewed
good job. I think the parts that has NIL in your comment should be removed since there is nothing to show

2019-08-27 13:45 UTC, daviddamilola commented
> good job. I think the parts that have NILL in your comment should be removed since there is nothing to show

The changes have been made

2019-08-27 14:35 UTC, ascii-dev commented on Dockerfile
> +CMD [ "node", "./build/index.js" ]
Kindly add a new line at the end of this file. Thanks

2019-08-27 14:56 UTC, daviddamilola commented on Dockerfile
> +CMD [ "node", "./build/index.js" ]
A new Line has been added.

> Kindly add a new line at the end of this file. Thanks

2019-08-28 09:25 UTC, hustlaviola approved these changes
Good job

2019-08-28 09:33 UTC, davidteejay approved these changes

2019-08-28 09:39 UTC, ibraheem-adeyemo approved these changes

2019-08-28 09:49 UTC, Naimaoye approved these changes

2019-08-28 09:50 UTC, ldonjibson approved these changes

2019-08-28 15:26 UTC, ascii-dev approved these changes
LGTM

2019-08-28 15:27 UTC, merged