#167749949 Implement JWT authentication
andela/magma-backend pull request #20
Opened 2019-09-03 06:32 UTC by hustlaviola

#### What does this PR do?

This PR implements JWT authentication and add it to user response on registration

#### Description of Tasks to be completed

- Update the test to have `token` property
- Remove `session` from the codebase
- Create a function to generate a token
- Create a function to authenticate the user
- Update signup function to return token
- Update Swagger documentation

#### How should this be manually tested?

- Clone the Repo, change into the directory and run `npm install`
- Run `npm dev` to start the server
- Make a `POST` request to `http://localhost:{PORT}/api/v1/user/signup` on Postman using valid credentials

Sample request body
```
{
    "email": "naimatjdavid@mail.com",
    "firstname": "Ibrahim",
    "lastname": "Jibson",
    "password": "ChibuokemAlabi99"
}
```

#### Relevant pivotal tracker story

[167749949](https://www.pivotaltracker.com/story/show/167749949)

#### Screenshot

![Screenshot (129)](https://user-images.githubusercontent.com/43535158/64149063-e18c8680-ce1c-11e9-8a59-f341f98ec3ee.png)

2019-09-07 09:02 UTC, ldonjibson approved these changes
Weldone @hustlaviola

2019-09-07 09:02 UTC, ldonjibson commented on src/middlewares/userValidations.js
> +const validateSignup = path => (req, res, next) => {
as disccussed make it generic

2019-09-09 08:24 UTC, daviddamilola requested changes
great work, however, the functionality of verifying token should be abstracted into its own function as it would be reused in other features you can name it `verifyToken(token)` and let it return the decoded object, it can belong to the helper class

2019-09-09 10:48 UTC, hustlaviola commented
> great work, however, the functionality of verifying token should be abstracted into its own function as it would be reused in other features you can name it `verifyToken(token)` and let it return the decoded object, it can belong to the helper class

Feedback implemented @daviddamilola. Thank you

2019-09-09 16:31 UTC, daviddamilola approved these changes

2019-09-11 06:18 UTC, hustlaviola commented on src/utils/userSchema.js
> +    email: Joi.string().required().label('Email is required'),
I think it's necessary to validate this email, a user may input a number or a 2 letter word, we don't have to check the database to see if it exists. Let's use the schema provided above for that.
```suggestion
    email,
```

2019-09-11 14:02 UTC, merged