#167749940 Configure Eslint to Report Patterns Found in JavaScript code
andela/magma-backend pull request #5
Opened 2019-08-15 16:28 UTC by alatos2

### What does this PR do?
Setup ESlint which  is the required linter for the project
### Description of Task to be completed?
Check for airbnb style violations and flag them.
### How should this be manually tested?
After configuration, codes written in es5 should be flagged.
### Any background context you want to provide?
N/A
### What are the relevant pivotal tracker stories?
#167749940
### Screenshots (if appropriate)
N/A
### Questions:
N/A

2019-08-15 20:08 UTC, hustlaviola requested changes
Good job on the configuration. You do need to edit your PR comment though, your `story id` should link to the story on PT board
You can use this format
`[story_id](https://www.pivotaltracker.com/story/show/story_id)`

2019-08-15 22:19 UTC, alatos2 commented
Thank you. Correction well received.

2019-08-17 18:17 UTC, hustlaviola approved these changes

2019-08-17 19:21 UTC, hustlaviola reviewed
Testing integration now.

2019-08-19 15:03 UTC, davidteejay approved these changes

2019-08-26 10:37 UTC, merged